### ISSUE TITLE
Add members to algorithm team

### ISSUE THREAD

**Issue by mykola-den** [kottans/algorithm_club#9]
hedgehogus
lysenko-sergei-developer
aleshaoleg
dumareckii
programulya
Alimova
veligura
ameks94
dm3shafieiev
amashoshyna
later +2 members 
read permissions on this repo.

@AMashoshyna @suchov  pls assign this issue.
additionally may i ask for @quodnon  write permission for this repo: to accept PR's and assign issues?

**Comment by suchov** [comment]
@Quodnon I made you an admin of this repo, so you now can add the team members yourself, will leave it up to you. Ping me if you'll need something else.

**Comment by mykola-den** [comment]
thank you @suchov 
![](http://www.gifbin.com/bin/052014/1399145865_cat_getting_ready_for_attack.gif)
